### PR TITLE
Replace Python's string templates with Jinja2

### PR DESCRIPTION
**Pull request by jeremyandrews**
This is part of #2, but primarily just re-works the existing templating using Jinja.

Minor improvements include:

- Leverage inheritance ( http://jinja.pocoo.org/docs/2.9/templates/#template-inheritance ) to share more code (more can be done)
- Added a proper footer
- Properly handle plurals: "1 device" vs "2 devices"

Not done:

- Creating a text version of all emails

### CODE REVIEW

**Review by natej — COMMENTED** [review]
I did a quick scan over the files and it looks good to me. This is a really nice feature.

It looks like Jinja is really close to Mako.

I haven't had time to setup a mailbox and try out the notifications, so I don't have any real feedback for you. A very minor, very low-priority nitpick :) ... I'd lower-case the HTML tags in the templates.

Looks really good!

**Comment by jeremyandrews** [comment]
I upper-cased the HTML tags intentionally, so they're differentiated from non-HTML tags. When they were lower case, it was hard to visually differentiate them from the Jinja tags and normal text, IMO.

**Comment by jeremyandrews** [comment]
I'm going to go ahead and commit and then iterate with followups. Overall it's working great only my local network, and is a good step forward.

**Comment by natej** [comment]
Great news. Looking forward to seeing it.

**Pull request merged**
